 var jsList = [
        "src/res/commonJs.js",
        "src/res/ccjJs.js",
        "src/resource.js",
        "src/config/lsyrs_cfg.js",
        "src/common/funcs.js",
        "src/layer/layerControl.js",
        "src/layer/myLayer.js",
        "src/layer/mainLayer.js",
        "src/layer/doLayer.js",
        "src/layer/helpLayer.js",
        "src/layer/seeLayer.js",
        "src/dialog/dialogControl.js",
        "src/dialog/exitDialog.js",
        "src/dialog/quitExpDialog.js",
        "src/dialog/tipsDialog.js",
        "src/common/extra.js",
        "src/common/timerControl.js",
        "src/common/toolAndvariable.js",

        "src/extra/lsyrs/learnLayer.js",
        "src/extra/lsyrs/seeExp1.js",
        "src/extra/lsyrs/doExp1.js",
        "src/extra/lsyrs/seeExp2.js",
        "src/extra/lsyrs/doExp2.js"
 ]