 var jsList = [
        "src/res/commonJs.js",
        "src/res/gsrJs.js",
        "src/resource.js",
        "src/config/rsxz_cfg.js",
        "src/common/funcs.js",
        "src/layer/layerControl.js",
        "src/layer/myLayer.js",
        "src/layer/mainLayer.js",
        "src/layer/doLayer.js",
        "src/layer/helpLayer.js",
        "src/layer/seeLayer.js",
        "src/layer/showLayer.js",
        "src/dialog/dialogControl.js",
        "src/dialog/exitDialog.js",
        "src/dialog/quitExpDialog.js",
        "src/dialog/tipsDialog.js",
        "src/dialog/showScoreDialog.js",
        "src/common/extra.js",
        "src/common/timerControl.js",
        "src/common/toolAndvariable.js",

        "src/extra/rsxz/learnLayer.js",
        "src/extra/rsxz/seeExp1.js",
        "src/extra/rsxz/doExp1.js"
 ]