 var jsList = [
        "src/res/commonJs.js",
        "src/res/ccjJs.js",
        "src/resource.js",
        "src/config/tyx_cfg.js",
        "src/common/funcs.js",
        "src/common/items.js",
        "src/layer/layerControl.js",
        "src/layer/myLayer.js",
        "src/layer/mainLayer.js",
        "src/layer/doLayer.js",
        "src/layer/helpLayer.js",
        "src/layer/seeLayer.js",
        "src/dialog/dialogControl.js",
        "src/dialog/exitDialog.js",
        "src/dialog/quitExpDialog.js",
        "src/dialog/tipsDialog.js",
        "src/dialog/judgeDialog.js",
        "src/common/extra.js",
        "src/common/timerControl.js",
        "src/common/toolAndvariable.js",

        "src/extra/tyx/learnLayer.js",
        "src/extra/tyx/doExp1.js",
        "src/extra/tyx/seeExp1.js"
 ]