 var jsList = [
    "src/res/commonJs.js",
    "src/res/lhJs.js",
    "src/resource.js",
    "src/config/wzdrj_cfg.js",
    "src/common/funcs.js",
    "src/common/items.js",
    "src/layer/layerControl.js",
    "src/layer/myLayer.js",
    "src/layer/mainLayer.js",
    "src/layer/doLayer.js",
    "src/layer/helpLayer.js",
    "src/layer/seeLayer.js",
    "src/dialog/dialogControl.js",
    "src/dialog/exitDialog.js",
    "src/dialog/quitExpDialog.js",
    "src/dialog/tipsDialog.js",
    "src/dialog/judgeDialog.js",
    "src/common/extra.js",
    "src/common/timerControl.js",

    "src/extra/wzdrj/learnLayer.js",
    "src/extra/wzdrj/doExp1.js",
    "src/extra/wzdrj/doExp2.js"
 ]